In [ ]:
# ndarray 是 多维数组 创建后大小固定 内存占用小 可向量化操作 快于list

import numpy as np

# 1维数组 (Vector)
a = np.array([1, 2, 3])

# 2维数组 (Matrix)
b = np.array([[1.5, 2, 3], [4, 5, 6]])

print(f"数组 a 的维度: {a.ndim}, 形状: {a.shape}\n")
print(f"数组 b 的数据类型: {b.dtype}\n") # float64
print(a)
print()
print(b)

数组 a 的维度: 1, 形状: (3,)

数组 b 的数据类型: float64

[1 2 3]

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [14]:
# NumPy 数组在内存中 连续存储
c = np.array([1, 2, 3], dtype='int32') 
# 每个int32元素占用 4 字节,每个float64元素占用8字节

arr1 = np.array([1, 2, 3], dtype='int8')   # 每个元素 1 字节
arr2 = np.array([1, 2, 3], dtype='int64')  # 每个元素 8 字节
print(f"int8 数组总字节数: {arr1.nbytes}") 
print(f"int64 数组总字节数: {arr2.nbytes}\n")


# 向量化是 代码中没有显式的 for 循环
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# 向量化写法
result = (x + y) * 2 
print(result)
print(x < 3)
print(np.sin(x))
print(np.exp(x))
print()
# 广播-较小数组 使之与较大数组形状匹配

a = np.array([1, 2, 3])
b = 2
print(a * b)  # [2, 4, 6] -> 标量 2 被广播到了数组的每一个元素


#  m 是 3x3 矩阵，n 是 1x3 向量
m = np.ones((3, 3))
n = np.array([1, 2, 3])
print(f'\nm是\n{m}\nn是{n}\n')
print(m + n) # n 会在行方向上“广播”三次，与 m 的每一行相加

int8 数组总字节数: 3
int64 数组总字节数: 24

[10 14 18]
[ True  True False]
[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]

[2 4 6]

m是
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
n是[1 2 3]

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
arr = np.arange(12) # 生成 0-11 的数组
print(arr)
print()

grid = arr.reshape(3, 4) # 3行4列
print(grid)
print()
# 自动计算维度：-1 表示让 NumPy 自己算（12 / 2 = 6）
cube = arr.reshape(2, 2, -1) # 把数组重排为三维数组（张量）
print(cube)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
